# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='img')),
                ('fechaInicio', models.DateField()),
                ('restriccion', models.CharField(max_length=200)),
                ('encargado', models.CharField(max_length=200)),
                ('hora', models.TimeField()),
                ('costo', models.IntegerField()),
                ('participante', models.IntegerField()),
                ('lugar', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('copete', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(max_length=10000)),
                ('autor', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='img')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='img')),
                ('fechaNacimiento', models.DateTimeField(verbose_name='date published')),
                ('genero', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usuarioEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.BooleanField(default=False)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte.evento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
