# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
