# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deporte', '0002_evento_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechaInicio', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFinal', models.TimeField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deporte.evento')),
            ],
        ),
    ]
