# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deporte', '0003_actividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
