# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deporte', '0005_evento_tipo_deporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioevento',
            name='estado',
            field=models.CharField(default='Pre-inscrito', max_length=130),
        ),
    ]
